# Generated by Django 4.0.5 on 2022-07-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='Titulo')),
                ('subtitulo', models.CharField(max_length=150, verbose_name='Subtitulo')),
                ('cuerpo', models.CharField(max_length=1600, verbose_name='Cuerpo')),
            ],
        ),
    ]
