# Generated by Django 4.0.5 on 2022-07-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hablemosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='cuerpo',
            field=models.CharField(max_length=1600, verbose_name='cuerpo'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='subtitulo',
            field=models.CharField(max_length=150, verbose_name='subtitulo'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='titulo',
            field=models.CharField(max_length=30, verbose_name='titulo'),
        ),
    ]
