# Generated by Django 4.0.5 on 2022-07-08 18:57

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hablemosapp', '0002_alter_debate_cuerpo_alter_debate_subtitulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='creado',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='debate',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debate',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='debate',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debate',
            name='cuerpo',
            field=models.TextField(verbose_name='cuerpo'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('creado', models.TimeField(default=django.utils.timezone.now)),
                ('dislike', models.ManyToManyField(blank=True, related_name='comentario_dislike', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='comentario_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
