# Generated by Django 4.0.5 on 2022-07-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hablemosapp', '0003_debate_creado_debate_dislike_debate_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='image',
        ),
        migrations.AddField(
            model_name='debate',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='', verbose_name='imagen'),
        ),
    ]
