# Generated by Django 4.0.5 on 2022-07-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hablemosapp', '0004_remove_debate_image_debate_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(verbose_name='comentario'),
        ),
    ]
