# Generated by Django 4.0.5 on 2022-07-09 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hablemosapp', '0005_alter_comentario_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='creado',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
