# Generated by Django 4.0.5 on 2022-07-09 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hablemosapp', '0006_alter_debate_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='creado',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
