# Generated by Django 4.0.5 on 2022-07-09 07:04

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hablemosapp', '0009_alter_debate_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='autor',
            field=models.TextField(default=django.contrib.auth.models.User),
        ),
    ]
