# Generated by Django 4.0.5 on 2022-07-09 09:01

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hablemosapp', '0010_debate_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='autor',
            field=models.TextField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
