# Generated by Django 4.0.5 on 2022-07-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hablemosapp', '0013_comentario_autor_comentario_debate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='postimage', verbose_name='imagen'),
        ),
    ]
