# Generated by Django 4.0.5 on 2022-07-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hablemosapp', '0015_alter_debate_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='titulo',
            field=models.CharField(max_length=60, verbose_name='titulo'),
        ),
    ]
