# Generated by Django 4.0.5 on 2022-07-15 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hablemosapp', '0019_alter_debate_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
