# Generated by Django 4.0.5 on 2022-07-20 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hablemosapp', '0024_alter_debate_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debate_autor', to=settings.AUTH_USER_MODEL),
        ),
    ]
