# Generated by Django 4.0.5 on 2022-07-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hablemosapp', '0028_mensaje_leido'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca')),
                ('creador', models.CharField(max_length=200, verbose_name='Creador')),
                ('descripcion', models.CharField(max_length=2000, verbose_name='Descripcion')),
            ],
        ),
    ]
