# Generated by Django 4.0.5 on 2022-07-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hablemosapp', '0029_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
    ]
